#!/usr/bin/env python

# Copyright (C) 2012  Volker Grabsch <vog@notjusthosting.com>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

import hashlib
import subprocess
import sys

class RemoteError(RuntimeError):
    pass

remote_script = r'''
import hashlib
import os
import os.path
import sys

filename = sys.stdin.readline().rstrip('\n')
size = int(sys.stdin.readline().rstrip('\n'))
blocksize = int(sys.stdin.readline().rstrip('\n'))
hashname = sys.stdin.readline().rstrip('\n')

if not os.path.exists(filename):
    # Create sparse file
    with open(filename, 'wb') as f:
        f.truncate(size)
    os.chmod(filename, 0600)

with open(filename, 'rb+') as f:
    f.seek(0, 2)
    if f.tell() != size:
        raise RuntimeError('Size mismatch (local: %i, remote: %i)' % (size, f.tell()))
    f.seek(0)
    sys.stdout.write('OK bscp 2a41278c-55e2-4e42-b1b5-847723b45225\n')
    while True:
        block = f.read(blocksize)
        if len(block) == 0:
            break
        hexdigest = hashlib.new(hashname, block).hexdigest()
        sys.stdout.write('%s\n' % (hexdigest,))
    sys.stdout.flush()
    while True:
        position_s = sys.stdin.readline()
        if len(position_s) == 0:
            break
        position = int(position_s.rstrip('\n'))
        block = sys.stdin.read(blocksize)
        f.seek(position)
        f.write(block)
    hash_total = hashlib.new(hashname)
    f.seek(0)
    while True:
        block = f.read(blocksize)
        if len(block) == 0:
            break
        hash_total.update(block)
sys.stdout.write('%s\n' % (hash_total.hexdigest(),))
'''

def bscp(local_filename, remote_host, remote_filename, blocksize=None, hashname=None):
    if blocksize is None:
        blocksize = 64 * 1024
    if hashname is None:
        hashname = 'sha1'

    with open(local_filename, 'rb') as f:
        f.seek(0, 2)
        size = f.tell()
        f.seek(0)

        # Calculate number of blocks, including the last block which may be smaller
        blockcount = int((size + blocksize - 1) / blocksize)

        remote_command = 'python -c "%s"' % (remote_script,)
        command = ('ssh', '--', remote_host, '--', remote_command)
        p = subprocess.Popen(command, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)

        if '\n' in remote_filename:
            raise RuntimeError('Invalid remote filename: %r' % (remote_filename,))
        if '\n' in hashname:
            raise RuntimeError('Invalid hash: %r' % (hashname,))
        p.stdin.write('%s\n%i\n%i\n%s\n' % (remote_filename, size, blocksize, hashname))

        remote_first = p.stdout.readline()
        if remote_first != 'OK bscp 2a41278c-55e2-4e42-b1b5-847723b45225\n':
            (remote_remaining_output, _) = p.communicate(None)
            raise RemoteError(remote_first + remote_remaining_output)

        remote_hexdigest_list = [p.stdout.readline().rstrip('\n') for i in xrange(blockcount)]

        hash_total = hashlib.new(hashname)
        for remote_hexdigest in remote_hexdigest_list:
            position = f.tell()
            block = f.read(blocksize)
            hash_total.update(block)
            hexdigest = hashlib.new(hashname, block).hexdigest()
            if hexdigest != remote_hexdigest:
                p.stdin.write('%i\n' % (position,))
                p.stdin.write(block)

        (remote_output, _) = p.communicate(None)
        if remote_output != '%s\n' % (hash_total.hexdigest(),):
            raise RuntimeError('Checksum mismatch (local: %r, remote: %r)' % (hash_total.hexdigest(), remote_output.rstrip('\n')))

if __name__ == '__main__':
    try:
        local_filename = sys.argv[1]
        (remote_host, remote_filename) = sys.argv[2].split(':')
        if len(sys.argv) >= 4:
            blocksize = int(sys.argv[3])
        else:
            blocksize = None
        if len(sys.argv) >= 5:
            hashname = sys.argv[4]
        else:
            hashname = None
        assert len(sys.argv) <= 5
    except:
        usage = 'bscp SRC HOST:DEST [BLOCKSIZE] [HASH]'
        sys.stderr.write('Usage:\n\n    %s\n\n' % (usage,))
        sys.exit(1)
    bscp(local_filename, remote_host, remote_filename, blocksize, hashname)
